message "called the program successfully".

message "but now we're going to throw an exception".

undo, throw new Progress.Lang.AppError("callMe.p exception").
